wandb_version: 1

dropout:
  desc: null
  value: 0.3
embed_dim:
  desc: null
  value: 64
num_epochs:
  desc: null
  value: 10
num_heads:
  desc: null
  value: 6
num_layers:
  desc: null
  value: 8
pool:
  desc: null
  value: max
post_enc:
  desc: null
  value: fixed
weight_decay:
  desc: null
  value: 0.0001
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707756237.670214
    t:
      1:
      - 1
      - 40
      - 55
      2:
      - 1
      - 40
      - 55
      3:
      - 23
      - 37
      4: 3.10.13
      5: 0.16.2
      8:
      - 3
      - 5
      13: windows-amd64
